import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald, Roboto } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["200", "500"],
});

// Note: DIN Next is not available on Google Fonts. Using a fallback.
// Consider purchasing DIN Next or using an alternative like Inter or Work Sans.
const dinNext = Geist({
  variable: "--font-din-next",
  subsets: ["latin"],
  weight: ["300"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = [
  { href: "/", label: "Home" },
  { href: "#builds", label: "Builds" },
  { href: "#guides", label: "Guides" },
  { href: "#useful-sites", label: "Useful Sites" },
  { href: "#about", label: "About" },
  { href: "#privacy-policy", label: "Privacy Policy" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} ${dinNext.variable} ${roboto.variable} antialiased`}
      >
        <div className="mx-auto w-full px-4 max-w-[1024px]">
          <header className="py-4">
            <h1 className="uppercase">Guides Not Included</h1>
            <p
              className="leading-[1.8em] text-center font-[300] text-[rgb(118,118,118)] border-b border-[var(--heading-primary)]"
              style={{
                fontFamily:
                  'var(--font-din-next), "din-next-w01-light", sans-serif',
              }}
            >
              Keep calm and press the space bar
            </p>
            <nav className="p-4 w-full">
              <ul className="flex gap-6 justify-center">
                {navLinks.map((link) => (
                  <li key={link.href} className="flex-1 relative">
                    <Link
                      href={link.href}
                      className="block px-2 text-center uppercase text-[15px] transition-colors duration-[400ms] hover:text-black font-[300] text-[#767676]"
                      style={{
                        fontFamily:
                          'var(--font-din-next), "din-next-w01-light", sans-serif',
                      }}
                    >
                      {link.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </nav>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
