import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["200", "500"],
});

// Note: DIN Next is not available on Google Fonts. Using a fallback.
// Consider purchasing DIN Next or using an alternative like Inter or Work Sans.
const dinNext = Geist({
  variable: "--font-din-next",
  subsets: ["latin"],
  weight: ["300"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} ${dinNext.variable} antialiased`}
      >
        <nav className="bg-gray-800 text-white p-4">
          <ul className="flex gap-6 justify-center">
            <li>
              <Link href="/" className="hover:underline">
                Home
              </Link>
            </li>
            <li>
              <Link href="#builds" className="hover:underline">
                Builds
              </Link>
            </li>
            <li>
              <Link href="#guides" className="hover:underline">
                Guides
              </Link>
            </li>
            <li>
              <Link href="#useful-sites" className="hover:underline">
                Useful Sites
              </Link>
            </li>
            <li>
              <Link href="#about" className="hover:underline">
                About
              </Link>
            </li>
            <li>
              <Link href="#privacy-policy" className="hover:underline">
                Privacy Policy
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
