import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["200", "500"],
});

// Note: DIN Next is not available on Google Fonts. Using a fallback.
// Consider purchasing DIN Next or using an alternative like Inter or Work Sans.
const dinNext = Geist({
  variable: "--font-din-next",
  subsets: ["latin"],
  weight: ["300"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} ${dinNext.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
